import Foundation

/// Traditional, gentle home remedies. Every remedy is made *with a grown-up*,
/// and every ailment screen reminds kids when to see a doctor.
enum RemedyPackages {
    static let all: [RemedyPackage] = [everydayCare, dadiNani, westIndia, eastIndia, paati, eastAsia, latin, mediterranean, western]

    /// Simple care that works everywhere. Always on, so every ailment mission can be solved.
    static let everydayCare = RemedyPackage(
        id: "everyday-care", name: "Everyday Care", emoji: "🩹",
        summary: "Rest, water, warm and cool tricks that work in every home.",
        remedies: [
            Remedy("salt-gargle", "Warm Salt-Water Gargle", "🧂", treats: [.soreThroat],
                   "Salt water pulls puffiness out of a swollen throat and washes germs away.",
                   steps: ["Grown-up mixes half a spoon of salt in a cup of warm water.", "Gargle, 'Gaa-gaa-gaa!', then spit it out.", "Repeat 3 times a day."],
                   diet: .vegan),
            Remedy("steam", "Steam Breathing", "♨️", treats: [.sniffles, .cough],
                   "Warm, wet air loosens the mucus so your nose and chest can clear.",
                   steps: ["Grown-up fills a bowl with hot water.", "Sit far enough away, cover your head with a towel.", "Breathe slowly for a few minutes."],
                   caution: "Hot water! Only with a grown-up, and never lean too close.", diet: .vegan),
            Remedy("slow-sips", "Slow Sips of Water", "🥤", treats: [.hiccups, .mildHeadache],
                   "Slow sips calm the jumpy diaphragm and refill a thirsty brain.",
                   steps: ["Take ten tiny sips of water, one after another.", "Breathe slowly through your nose."],
                   diet: .vegan),
            Remedy("shade-water", "Shade, Water & a Wet Cloth", "⛱️", treats: [.tooHot],
                   "Cooling down in the shade and drinking water brings your body temperature back down.",
                   steps: ["Move to a cool, shady spot.", "Sip water slowly.", "Put a cool wet cloth on your neck and forehead."],
                   diet: .vegan),
            Remedy("rinse-dentist", "Rinse & Tell a Grown-up", "🪥", treats: [.toothache],
                   "Rinsing removes stuck food. A grown-up can check if a dentist visit is needed.",
                   steps: ["Swish warm water around your mouth.", "Gently floss around the sore tooth.", "Show a grown-up where it hurts."],
                   diet: .vegan),
            Remedy("cold-compress", "Cold Compress", "🧊", treats: [.itchyBite, .mildHeadache],
                   "Cold makes the swelling and itch shrink, and calms a thumpy head.",
                   steps: ["Wrap ice in a clean cloth (never ice straight on skin).", "Hold it on the spot for a few minutes."],
                   diet: .vegan),
            Remedy("rest-stretch", "Rest & Gentle Stretches", "🧘", treats: [.tiredMuscles],
                   "Muscles repair themselves while you rest. Gentle stretches help blood bring them food.",
                   steps: ["Lie down with your legs up on a pillow.", "Do slow, gentle stretches. No bouncing!"],
                   diet: .vegan),
            Remedy("wash-face", "Wash Face & Change Clothes", "🚿", treats: [.sneezyAllergy],
                   "Pollen sticks to skin, hair and clothes. Washing it off means fewer sneezes.",
                   steps: ["Wash your face and hands after playing outside.", "Change into fresh clothes.", "Keep windows closed on windy pollen days."],
                   diet: .vegan),
            Remedy("look-far", "Fresh Air & Look Far Away", "🪟", treats: [.travelTummy],
                   "Looking at the far horizon helps your eyes and ears agree, and fresh air settles the tummy.",
                   steps: ["Open the window a little.", "Look far away, not at a book or screen.", "Take slow, deep breaths."],
                   diet: .vegan),
            Remedy("water-fruit-walk", "Water, Fruit & a Walk", "🚶", treats: [.stuckTummy],
                   "Water softens, fruit fiber sweeps, and walking wakes up a lazy tummy.",
                   steps: ["Drink a big glass of water.", "Eat a fruit like papaya or guava.", "Go for a short walk."],
                   diet: .vegan),
            Remedy("warm-bottle", "Warm Water Bottle & Rest", "🫖", treats: [.tummyAche],
                   "Gentle warmth relaxes tight tummy muscles.",
                   steps: ["Grown-up fills a bottle with warm (not hot!) water.", "Lie down and rest it on your tummy."],
                   caution: "Make sure it's warm, not hot.", diet: .vegan),
        ],
        isCore: true
    )

    static let dadiNani = RemedyPackage(
        id: "dadi-nani", name: "Dadi-Nani ke Nuskhe", emoji: "👵🏽",
        summary: "North Indian grandmother cures: adrak-tulsi, haldi doodh, laung, ajwain and hing.",
        remedies: [
            Remedy("ginger-lemon-tea", "Ginger Lemon Honey Tea", local: "Adrak Nimbu Shahad", "🍋", treats: [.soreThroat, .cough, .sniffles],
                   "Ginger has gingerol that calms swelling, lemon brings vitamin C, and honey coats a scratchy throat.",
                   steps: ["Grown-up boils a few slices of ginger in water.", "Let it cool till warm, then add lemon and a spoon of honey.", "Sip slowly."],
                   diet: .vegetarian),
            Remedy("tulsi-kadha", "Tulsi Adrak Kadha", local: "Kadha", "🌿", treats: [.sniffles, .cough, .soreThroat],
                   "Tulsi (holy basil) leaves have oils that help open a stuffy nose and fight germs.",
                   steps: ["Boil 5 tulsi leaves, a slice of ginger and a pinch of black pepper in water.", "Strain, add a little gur or honey.", "Sip while warm."],
                   diet: .vegan),
            Remedy("haldi-doodh", "Haldi Doodh", local: "Golden Milk", "🥛", treats: [.tiredMuscles, .cough],
                   "Turmeric's curcumin calms sore, swollen spots. Warm milk helps you sleep and heal.",
                   steps: ["Warm a cup of milk with a pinch of turmeric and black pepper.", "Drink it before bed."],
                   allergens: [.dairy]),
            Remedy("laung", "Clove for a Toothache", local: "Laung", "🦷", treats: [.toothache],
                   "Clove has eugenol, a natural numbing oil that quiets an achy tooth for a while.",
                   steps: ["Grown-up places one whole clove gently near the sore tooth.", "Hold it there; don't chew hard.", "Still see a dentist!"],
                   caution: "Only a grown-up should use clove oil, and never swallow it.", diet: .vegan),
            Remedy("ajwain-namak", "Ajwain with Kala Namak", "🌱", treats: [.tummyAche],
                   "Ajwain's thymol helps break up gas bubbles in a grumbly tummy.",
                   steps: ["Grown-up mixes a pinch of roasted ajwain and black salt.", "Chew it and sip warm water."],
                   diet: .vegan),
            Remedy("hing-paste", "Hing Paste on the Tummy", local: "Hing", "🟡", treats: [.tummyAche],
                   "A Marwari and Baniya favourite: hing (asafoetida) warms the tummy and eases gas.",
                   steps: ["Grown-up mixes a pinch of hing with a few drops of warm water.", "Rub it gently around the belly button."],
                   diet: .vegan),
            Remedy("saunf-mishri", "Saunf Mishri", "💚", treats: [.tummyAche, .travelTummy],
                   "Fennel seeds relax the tummy muscles and freshen your breath.",
                   steps: ["Chew half a spoon of saunf with a crystal of mishri after meals."],
                   diet: .vegan),
            Remedy("elaichi", "Chew an Elaichi", local: "Elaichi", "🫛", treats: [.travelTummy],
                   "Cardamom's fragrance settles a queasy, wobbly tummy on long rides.",
                   steps: ["Chew one green cardamom pod slowly while you travel."],
                   diet: .vegan),
            Remedy("kishmish", "Soaked Kishmish & Anjeer", "🍇", treats: [.stuckTummy],
                   "Soaked raisins and figs are full of soft fiber that gets a stuck tummy moving.",
                   steps: ["Soak 8 raisins and 1 fig in water overnight.", "Eat them in the morning and drink the water."],
                   diet: .vegan),
            Remedy("aam-panna", "Aam Panna", "🥭", treats: [.tooHot],
                   "Raw mango drink with jeera and salt puts back the salts you sweat out on hot days.",
                   steps: ["Grown-up boils raw mango and blends the pulp.", "Mix with water, roasted jeera, black salt and a little gur.", "Drink cool, not icy."],
                   diet: .vegan),
            Remedy("honey-pepper", "Honey & Black Pepper", "🍯", treats: [.cough],
                   "Honey soothes a tickly throat, and pepper helps loosen the cough.",
                   steps: ["Mix a spoon of honey with a tiny pinch of black pepper.", "Lick it slowly."],
                   caution: "Honey is fine for big kids, never for babies under one year.", diet: .vegetarian),
            Remedy("haldi-lep", "Haldi Lep", "🟠", treats: [.itchyBite],
                   "A paste of turmeric calms the swelling around an itchy bite.",
                   steps: ["Grown-up mixes turmeric with a few drops of water.", "Dab a little on the bite. Try not to scratch!"],
                   diet: .vegan),
        ]
    )

    static let westIndia = RemedyPackage(
        id: "west-india", name: "Gujarati, Marwari & Marathi Gharelu Upay", emoji: "🪁",
        summary: "Sunth goli, raab, chaas, kokum and variyali from western India.",
        remedies: [
            Remedy("sunth-goli", "Sunth Gud Goli", "🟤", treats: [.soreThroat, .sniffles],
                   "Dry ginger and jaggery balls warm the throat. A Gujarati winter staple.",
                   steps: ["Grown-up mixes sunth powder, a little ghee and gur into tiny balls.", "Eat one ball with warm water."],
                   allergens: [.dairy]),
            Remedy("raab-remedy", "Warm Bajra Raab", local: "Raab", "🥣", treats: [.sniffles, .cough],
                   "A warm, thin bajra porridge with ajwain and sunth, made when kids have a cold.",
                   steps: ["Grown-up roasts bajra flour in a little ghee.", "Adds water, gur, ajwain and sunth and cooks till thin.", "Sip it warm."],
                   allergens: [.dairy]),
            Remedy("jeera-chaas", "Jeera Chaas", "🥛", treats: [.tooHot, .tummyAche],
                   "Buttermilk with roasted jeera cools you and has friendly bacteria for the tummy.",
                   steps: ["Whisk curd with water.", "Add roasted jeera and a pinch of salt."],
                   allergens: [.dairy]),
            Remedy("kokum-sharbat", "Kokum Sharbat", "🩷", treats: [.tooHot],
                   "Kokum from the Konkan coast is a natural cooler on a blazing day.",
                   steps: ["Soak kokum in water, then strain.", "Add jeera and a little jaggery."],
                   diet: .vegan),
            Remedy("variyali-sharbat", "Variyali Sharbat", "💚", treats: [.tooHot, .tummyAche],
                   "Fennel seed sherbet is cooling and gentle on the tummy.",
                   steps: ["Soak saunf overnight and grind it.", "Strain into cool water with a little mishri."],
                   diet: .vegan),
            Remedy("ajwain-potli", "Ajwain Potli", "👝", treats: [.sniffles],
                   "A warm cloth bundle of roasted ajwain gives a soothing smell that opens a stuffy nose.",
                   steps: ["Grown-up roasts ajwain and ties it in a cotton cloth.", "Check it's warm, not hot, and hold it near your chest and nose."],
                   caution: "Grown-up checks the temperature first.", diet: .vegan),
            Remedy("methi-dana", "Soaked Methi Dana", "🌾", treats: [.stuckTummy],
                   "Soaked fenugreek seeds turn slippery and help a stuck tummy.",
                   steps: ["Soak half a spoon of methi seeds overnight.", "Swallow them with the water in the morning."],
                   diet: .vegan),
        ]
    )

    static let eastIndia = RemedyPackage(
        id: "east-india", name: "Odia, Bengali & Bihari Totke", emoji: "🛕",
        summary: "Pakhala, bel pana, sattu, thankuni and sorse tel from eastern India.",
        remedies: [
            Remedy("pakhala-remedy", "Pakhala Pani", "🍚", treats: [.tooHot],
                   "Fermented rice water from Odisha keeps you cool and gives salts and good bacteria.",
                   steps: ["Soak cooked rice in water overnight.", "Drink the water with salt and a squeeze of lime."],
                   diet: .vegan),
            Remedy("bel-pana", "Bel Pana", "🟠", treats: [.tooHot, .stuckTummy],
                   "Wood-apple drink made for Pana Sankranti. Cools you down and its fiber helps the tummy.",
                   steps: ["Scoop out bel pulp and soak it in water.", "Mash, strain, and add a little jaggery."],
                   diet: .vegan),
            Remedy("sattu-remedy", "Namkeen Sattu Ghol", "🥤", treats: [.tooHot],
                   "Bihar's summer saviour: roasted gram in salted lemon water.",
                   steps: ["Stir two spoons of sattu into cold water.", "Add salt, roasted jeera and lemon."],
                   diet: .vegan),
            Remedy("thankuni", "Thankuni Pata Bata", "🍀", treats: [.tummyAche],
                   "Bengali grandmothers grind thankuni (Indian pennywort) leaves for upset tummies.",
                   steps: ["Grind a few thankuni leaves with a pinch of salt.", "Eat a little with the first bite of rice."],
                   diet: .vegan),
            Remedy("sorse-tel", "Warm Mustard Oil Massage", local: "Sorse Tel Malish", "🫙", treats: [.tiredMuscles, .sniffles],
                   "Gently warmed mustard oil with garlic is rubbed on legs and chest to warm and soothe.",
                   steps: ["Grown-up warms mustard oil with a garlic clove.", "Cool it till warm, then massage legs, soles and chest."],
                   caution: "Grown-up checks the oil isn't hot.", diet: .vegan),
            Remedy("tulsi-madhu", "Tulsi Pata & Madhu", "🌿", treats: [.cough, .soreThroat],
                   "Tulsi juice with honey, a classic for coughs in Bengal and Odisha.",
                   steps: ["Crush a few tulsi leaves to get juice.", "Mix with a spoon of honey and lick slowly."],
                   diet: .vegetarian),
        ]
    )

    static let paati = RemedyPackage(
        id: "paati", name: "Paati Vaidhyam (South India)", emoji: "🌺",
        summary: "Rasam, sukku malli kaapi, karpooravalli, neer mor and kanji.",
        remedies: [
            Remedy("milagu-rasam", "Milagu Jeera Rasam", "🍲", treats: [.sniffles, .soreThroat, .cough],
                   "Pepper and cumin rasam is hot and spicy; it opens a blocked nose and warms the throat.",
                   steps: ["Grown-up boils tamarind water with tomato, pepper, jeera and garlic.", "Add a ghee-mustard tadka.", "Sip from a cup or have it with rice."],
                   diet: .vegan),
            Remedy("sukku-kaapi", "Sukku Malli Kaapi", "☕️", treats: [.sniffles, .soreThroat],
                   "No coffee in it! Dry ginger and coriander seeds boiled with palm jaggery.",
                   steps: ["Boil dry ginger, coriander seeds and pepper in water.", "Add karupatti (palm jaggery) and strain."],
                   diet: .vegan),
            Remedy("karpooravalli", "Karpooravalli Leaf", local: "Doddapatre / Panikoorka", "🍃", treats: [.cough],
                   "Indian borage leaves are thick and fragrant, and their juice soothes a cough.",
                   steps: ["Warm a leaf over the flame, squeeze out the juice.", "Mix with honey and lick."],
                   diet: .vegetarian),
            Remedy("neer-mor", "Neer Mor", "🥛", treats: [.tooHot],
                   "Thin, spiced buttermilk handed out to everyone in Tamil summers.",
                   steps: ["Thin curd with lots of water.", "Add curry leaves, ginger and salt."],
                   allergens: [.dairy]),
            Remedy("kanji-remedy", "Rice Kanji", "🥣", treats: [.tummyAche],
                   "Kerala's rice gruel is the gentlest food for a sick tummy, with water and salts.",
                   steps: ["Cook rice in lots of water until soft.", "Add salt and sip it warm."],
                   diet: .vegan),
            Remedy("inji-murabba", "Inji Murappa", "🫚", treats: [.travelTummy],
                   "Ginger candy is the South Indian travel trick for wobbly tummies.",
                   steps: ["Suck a small piece of ginger-jaggery candy slowly during the trip."],
                   diet: .vegan),
        ]
    )

    static let eastAsia = RemedyPackage(
        id: "east-asia", name: "East Asian Home Remedies", emoji: "🥢",
        summary: "Ginger tea, congee, barley tea, yuja-cha and steamed pear from China, Japan and Korea.",
        remedies: [
            Remedy("ginger-tea-asia", "Brown Sugar Ginger Tea", local: "Jiāng Chá", "🫖", treats: [.travelTummy, .sniffles],
                   "Warm ginger tea is used across China and Korea to settle tummies and warm up after a chill.",
                   steps: ["Simmer sliced ginger in water.", "Add a little brown sugar and sip."],
                   diet: .vegan),
            Remedy("okayu", "Okayu / Congee", "🥣", treats: [.tummyAche],
                   "Soft rice porridge, what Japanese and Chinese families eat when tummies are upset.",
                   steps: ["Simmer rice in lots of water for an hour.", "Add a pinch of salt."],
                   diet: .vegan),
            Remedy("barley-tea", "Barley Tea", local: "Mugicha / Boricha", "🍵", treats: [.tooHot],
                   "Roasted barley tea served cold is summer's favourite drink in Japan and Korea.",
                   steps: ["Steep roasted barley in water.", "Chill and drink."],
                   diet: .vegan, allergens: [.gluten]),
            Remedy("yuja-cha", "Yuja-cha", "🍋", treats: [.soreThroat],
                   "Korean citron marmalade tea, full of vitamin C, soothes a scratchy throat.",
                   steps: ["Stir a spoon of yuja marmalade into warm water."],
                   diet: .vegan),
            Remedy("steamed-pear", "Steamed Pear with Honey", local: "Baesuk / Xuělí", "🍐", treats: [.cough],
                   "Pear steamed with honey and jujube is a gentle cough soother in Korea and China.",
                   steps: ["Grown-up cores a pear and fills it with honey.", "Steam until soft and eat it warm."],
                   diet: .vegetarian),
        ]
    )

    static let latin = RemedyPackage(
        id: "latin", name: "Remedios de la Abuela", emoji: "🌵",
        summary: "Manzanilla, limón con miel, caldo, sábila and agua fresca from Latin America.",
        remedies: [
            Remedy("manzanilla", "Té de Manzanilla", "🌼", treats: [.tummyAche],
                   "Chamomile tea relaxes the tummy and helps you rest.",
                   steps: ["Steep chamomile flowers in hot water.", "Let it cool till warm and sip."],
                   diet: .vegan),
            Remedy("limon-miel", "Limón con Miel", "🍋", treats: [.soreThroat, .cough],
                   "Warm lime and honey: vitamin C plus a soothing coat for the throat.",
                   steps: ["Squeeze lime into warm water.", "Add a spoon of honey."],
                   diet: .vegetarian),
            Remedy("caldo", "Caldo de Pollo", "🍲", treats: [.sniffles],
                   "Warm chicken broth with vegetables keeps you hydrated and helps clear a stuffy nose.",
                   steps: ["Sip warm broth with carrots, squash and a squeeze of lime."],
                   diet: .nonVegetarian),
            Remedy("sabila", "Sábila (Aloe Vera)", "🪴", treats: [.itchyBite],
                   "Cool aloe gel calms itchy, swollen skin.",
                   steps: ["Grown-up cuts an aloe leaf.", "Dab the clear gel on the bite."],
                   diet: .vegan),
            Remedy("agua-pepino", "Agua Fresca de Pepino", "🥒", treats: [.tooHot],
                   "Cucumber-lime water is cooling and refreshing.",
                   steps: ["Blend cucumber with water and lime.", "Strain and drink cool."],
                   diet: .vegan),
            Remedy("hierbabuena", "Té de Hierbabuena", "🌱", treats: [.travelTummy, .tummyAche],
                   "Mint tea calms a queasy tummy.",
                   steps: ["Steep fresh mint leaves in hot water.", "Cool a little and sip."],
                   diet: .vegan),
        ]
    )

    static let mediterranean = RemedyPackage(
        id: "mediterranean", name: "Mediterranean & Middle Eastern", emoji: "🫒",
        summary: "Sage tea, fennel tea, ayran and chicken soup from Greece to the Levant.",
        remedies: [
            Remedy("faskomilo", "Sage Tea", local: "Faskomilo", "🌿", treats: [.soreThroat],
                   "Greek grandmothers make sage tea with honey for sore throats.",
                   steps: ["Steep a few sage leaves in hot water.", "Add honey and lemon when warm."],
                   diet: .vegetarian),
            Remedy("fennel-tea", "Fennel Tea", "💚", treats: [.tummyAche],
                   "Fennel seed tea eases gas bubbles.",
                   steps: ["Crush a spoon of fennel seeds and steep in hot water.", "Strain and sip warm."],
                   diet: .vegan),
            Remedy("ayran", "Ayran / Doogh", "🥛", treats: [.tooHot],
                   "Salted yogurt drink that cools you down in Turkish and Persian summers.",
                   steps: ["Whisk yogurt with cold water and a pinch of salt.", "Add dried mint for doogh."],
                   allergens: [.dairy]),
            Remedy("chicken-soup-remedy", "Grandma's Chicken Soup", "🍲", treats: [.sniffles],
                   "Warm soup keeps you hydrated, and the steam helps a stuffy nose.",
                   steps: ["Sip warm chicken broth with carrots and celery."],
                   diet: .nonVegetarian),
            Remedy("prunes", "Stewed Prunes & Figs", "🟣", treats: [.stuckTummy],
                   "Dried plums and figs are packed with soft fiber.",
                   steps: ["Simmer a few prunes and figs in water.", "Eat them warm."],
                   diet: .vegan),
        ]
    )

    static let western = RemedyPackage(
        id: "western-remedies", name: "American & European Home Care", emoji: "🏡",
        summary: "Honey-lemon, ginger chews, oatmeal baths and peppermint.",
        remedies: [
            Remedy("honey-lemon", "Warm Honey Lemon Water", "🍯", treats: [.soreThroat, .cough],
                   "Honey coats the throat and lemon brings vitamin C.",
                   steps: ["Stir honey and lemon juice into warm water."],
                   diet: .vegetarian),
            Remedy("ginger-chews", "Ginger Chews", "🫚", treats: [.travelTummy],
                   "Ginger candies help settle motion sickness.",
                   steps: ["Chew one ginger chew slowly during the ride."],
                   diet: .vegan),
            Remedy("oatmeal-bath", "Oatmeal Bath", "🛁", treats: [.itchyBite],
                   "Finely ground oats in a lukewarm bath calm itchy skin.",
                   steps: ["Grown-up blends oats into powder.", "Mix into a lukewarm bath and soak."],
                   diet: .vegan),
            Remedy("peppermint", "Peppermint Tea", "🌱", treats: [.tummyAche],
                   "Peppermint relaxes tummy muscles.",
                   steps: ["Steep peppermint leaves in hot water.", "Let it cool till warm."],
                   diet: .vegan),
        ]
    )
}
