import Foundation

/// "Tiffin Tales": {name} and Tiffy, a talking steel tiffin box from Dadi's
/// kitchen, go through one big year of small adventures. Each mission is a
/// bite-sized tricky spot that the right food or home remedy fixes.
enum StoryContent {
    static let companionName = "Tiffy"

    static let prologue = """
    On {name}'s birthday, Dadi gave a very special present: a shiny steel tiffin box. \
    When {name} opened the lid, it giggled! "Hello! I'm Tiffy. I carry the recipes of \
    every grandma in the world. Whenever you're stuck, open me up, and together we'll \
    find the food that helps!"
    """

    static let chapters: [Chapter] = [
        Chapter(id: "c1", number: 1, title: "The Sleepy Monday", emoji: "🏫",
                intro: "A brand new school week! But Monday has a few surprises.", tint: 0, missions: [
            Mission(id: "c1m1", title: "Can't Get Out of Bed", scene: "🛏️⏰",
                    situation: "The alarm is ringing, but {name} feels like a floppy noodle. The school bus comes in 20 minutes!",
                    kind: .meal(needs: [.energy, .stamina], avoid: nil), stuckMood: .sleepy,
                    successText: "{name} jumps out of bed, brushes, and catches the bus with a big wave!", successEmoji: "🚌"),
            Mission(id: "c1w1", title: "Breakfast Before School", scene: "🌅🥣",
                    situation: "{name} is rushing out the door with one shoe on and an empty tummy. {elder} is standing at the kitchen door, arms folded.",
                    kind: .wisdom(.breakfast), stuckMood: .worried,
                    successText: "{name} eats a proper breakfast and walks into class bright and ready.", successEmoji: "🎒"),
            Mission(id: "c1m2", title: "The Spelling Bee", scene: "🐝📝",
                    situation: "Ms. Rao calls out 'ELEPHANT'. {name}'s brain feels foggy, and the letters are jumbling up!",
                    kind: .meal(needs: [.focus], avoid: nil), stuckMood: .worried,
                    successText: "E-L-E-P-H-A-N-T! {name} spells it perfectly. The class claps!", successEmoji: "🏅"),
            Mission(id: "c1m3", title: "The Heavy Library Books", scene: "📚📚",
                    situation: "It's {name}'s turn to carry the class library books. The pile is so heavy, arms are wobbling!",
                    kind: .meal(needs: [.strength, .bones], avoid: nil), stuckMood: .tired,
                    successText: "{name} carries the whole pile to the library without a wobble.", successEmoji: "💪"),
            Mission(id: "c1m4", title: "Scratchy Throat", scene: "🧊🥤",
                    situation: "After an icy drink at recess, {name}'s throat feels scratchy and it hurts to talk.",
                    kind: .remedy(.soreThroat), stuckMood: .sick,
                    successText: "The throat feels soothed. {name} can sing in music class again!", successEmoji: "🎵"),
        ]),

        Chapter(id: "c2", number: 2, title: "Sports Day Surprise", emoji: "🏃",
                intro: "Sports Day is in one week, and {name} is in the relay team!", tint: 1, missions: [
            Mission(id: "c2m1", title: "Huffing After One Lap", scene: "🏟️💨",
                    situation: "Coach blows the whistle. After just one lap, {name} is huffing and puffing.",
                    kind: .meal(needs: [.stamina, .energy], avoid: nil), stuckMood: .tired,
                    successText: "{name} runs three whole laps and still has breath to cheer!", successEmoji: "🏃"),
            Mission(id: "c2w1", title: "Coach's Sprout Secret", scene: "🌱🏅",
                    situation: "Coach says champions eat sprouts. At home, {elder} has a bowl of plain moong and a damp cloth.",
                    kind: .wisdom(.sprouting), stuckMood: .worried,
                    successText: "Two days later, tiny white tails pop out! {name} has a super-sprout snack for practice.", successEmoji: "🌱"),
            Mission(id: "c2m2", title: "Stiff as a Stick", scene: "🧘🤸",
                    situation: "Yoga warm-ups! But {name} can't touch toes; legs feel stiff as a stick.",
                    kind: .meal(needs: [.flexibility, .hydration], avoid: nil), stuckMood: .worried,
                    successText: "Stretch, bend, touch! {name} does a perfect butterfly pose.", successEmoji: "🦋"),
            Mission(id: "c2m3", title: "Hot Afternoon Practice", scene: "☀️🥵",
                    situation: "The sun is blazing. {name} feels dizzy and droopy in the middle of practice.",
                    kind: .remedy(.tooHot), stuckMood: .sick,
                    successText: "Cool and refreshed, {name} is ready to practice again, in the shade!", successEmoji: "⛱️"),
            Mission(id: "c2w2", title: "The Team's Summer Drink", scene: "☀️🥤",
                    situation: "The whole team is hot and thirsty after practice. {elder} offers to make a drink for everyone.",
                    kind: .wisdom(.summerCooler), stuckMood: .worried,
                    successText: "The team cheers, cool and refreshed, and {name} knows the family recipe!", successEmoji: "🥤"),
            Mission(id: "c2m4", title: "Sore Legs Morning", scene: "🦵😖",
                    situation: "The day after practice, {name}'s legs ache with every step down the stairs.",
                    kind: .remedy(.tiredMuscles), stuckMood: .tired,
                    successText: "The legs feel loose and happy again. Muscles grow stronger with rest!", successEmoji: "🌟"),
            Mission(id: "c2m5", title: "The Relay Final", scene: "🏁🥇",
                    situation: "It's the final race! {name} has to run fast AND catch the baton without dropping it.",
                    kind: .meal(needs: [.stamina, .strength, .focus], avoid: nil), stuckMood: .worried,
                    successText: "Catch, zoom, finish! {name}'s team wins the relay!", successEmoji: "🥇"),
        ]),

        Chapter(id: "c3", number: 3, title: "Holidays at Nani's Village", emoji: "🌾",
                intro: "Summer holidays! {name} and Tiffy are off to Nani's village.", tint: 2, missions: [
            Mission(id: "c3m1", title: "Wobbly Train Ride", scene: "🚂🌀",
                    situation: "The train rocks side to side, and {name}'s tummy is wobbling with it.",
                    kind: .remedy(.travelTummy), stuckMood: .sick,
                    successText: "Tummy settled, {name} counts cows and fields out of the window.", successEmoji: "🐄"),
            Mission(id: "c3m2", title: "Helping in the Garden", scene: "🪴🪣",
                    situation: "Nani needs help carrying water buckets and bending to plant seeds.",
                    kind: .meal(needs: [.strength, .flexibility], avoid: nil), stuckMood: .tired,
                    successText: "Bucket by bucket, seed by seed. The whole garden is planted!", successEmoji: "🌱"),
            Mission(id: "c3w1", title: "Lunch Under the Neem Tree", scene: "🌳🍛",
                    situation: "Lunch at Nani's! {elder} says, 'Every dish has a best friend. Can you guess who it is?'",
                    kind: .wisdom(.grainPartner), stuckMood: .worried,
                    successText: "{name} matches every dish with its best friend. Nani laughs: 'You know more than your parents!'", successEmoji: "🤝"),
            Mission(id: "c3m3", title: "Mosquito Party", scene: "🦟🌙",
                    situation: "Evening in the courtyard, and a mosquito bit {name}'s arm. It is SO itchy!",
                    kind: .remedy(.itchyBite), stuckMood: .worried,
                    successText: "The itch calms down. Tonight {name} sleeps under the mosquito net!", successEmoji: "🕸️"),
            Mission(id: "c3w2", title: "The Bowl by the Window", scene: "💧🫘",
                    situation: "Before bed, {name} sees {elder} pour beans into a big bowl of water and leave it by the window.",
                    kind: .wisdom(.soaking), stuckMood: .worried,
                    successText: "Next day the beans are plump and soft, and they cook in no time!", successEmoji: "🫘"),
            Mission(id: "c3w3", title: "The Rajma Secret", scene: "🫘🟡",
                    situation: "Rajma for dinner! But last time, everyone's tummy puffed up like a balloon afterwards.",
                    kind: .wisdom(.beansGas), stuckMood: .worried,
                    successText: "Rajma night with happy tummies all round!", successEmoji: "🎈"),
            Mission(id: "c3m4", title: "Too Many Laddoos", scene: "🍬🦷",
                    situation: "After the village fair and lots of sweets, one of {name}'s teeth starts to ache.",
                    kind: .remedy(.toothache), stuckMood: .sick,
                    successText: "The ache calms down. {name} promises to brush twice a day, and Nani books a dentist visit.", successEmoji: "🪥"),
            Mission(id: "c3m5", title: "Nani's Cooking Lesson", scene: "👵🏽🍳",
                    situation: "Nani is teaching {name} a family recipe. It needs careful measuring and a steady, calm mind.",
                    kind: .meal(needs: [.focus, .calm], avoid: nil), stuckMood: .worried,
                    successText: "Perfectly measured! Nani says {name} cooks just like she did as a child.", successEmoji: "🥘"),
            Mission(id: "c3e1", title: "Ask Nani a Question", scene: "🎙️👵🏽",
                    situation: "On the last night of the holidays, Tiffy has an idea: 'Grandparents know things that aren't in any book. Go and ask!'",
                    kind: .askElder(question: WisdomContent.elderQuestions[2]), stuckMood: .happy,
                    successText: "{name} saved the answer in the Wisdom Book, to keep forever.", successEmoji: "📜"),
        ]),

        Chapter(id: "c4", number: 4, title: "Monsoon Mysteries", emoji: "🌧️",
                intro: "The rains are here! Puddles, paper boats and a few sniffles.", tint: 3, missions: [
            Mission(id: "c4m1", title: "Rainy Day Sniffles", scene: "☔️🤧",
                    situation: "Splash! {name} got soaked in the rain, and now the nose won't stop dripping.",
                    kind: .remedy(.sniffles), stuckMood: .sick,
                    successText: "Nose clear, {name} can smell the wet earth again!", successEmoji: "🌈"),
            Mission(id: "c4w1", title: "Haldi's Tiny Friend", scene: "🌧️🟠",
                    situation: "It's a rainy evening and {elder} is making a warm haldi dal. Tiffy says something tiny is missing.",
                    kind: .wisdom(.haldiPepper), stuckMood: .worried,
                    successText: "The dal is golden and peppery, and {name} feels cosy inside.", successEmoji: "🍲"),
            Mission(id: "c4m2", title: "Germ Shield Up!", scene: "🦠🛡️",
                    situation: "Half the class is sneezing. {name} needs a germ shield to stay well this week.",
                    kind: .meal(needs: [.immunity, .tummy], avoid: nil), stuckMood: .worried,
                    successText: "Shield up! {name} stays healthy all week long.", successEmoji: "🛡️"),
            Mission(id: "c4w2", title: "Shy Iron", scene: "🥬🍋",
                    situation: "Palak dal for dinner! Tiffy whispers, 'The iron inside is shy. It needs a friend to help it out!'",
                    kind: .wisdom(.ironHelper), stuckMood: .worried,
                    successText: "With its friend's help, the iron gets to work. {name} feels sharp and bright!", successEmoji: "✨"),
            Mission(id: "c4m3", title: "Coughing at Night", scene: "🌙😮‍💨",
                    situation: "It's bedtime, but a tickly cough keeps waking {name} up.",
                    kind: .remedy(.cough), stuckMood: .sick,
                    successText: "The cough quiets down, and {name} sleeps through the night.", successEmoji: "😴"),
            Mission(id: "c4m4", title: "Paper Boat Fleet", scene: "⛵️📄",
                    situation: "{name} wants to fold 10 paper boats for the puddle race. Folding needs patient, careful fingers.",
                    kind: .meal(needs: [.focus, .calm], avoid: nil), stuckMood: .worried,
                    successText: "Ten perfect boats sail down the puddle river!", successEmoji: "⛵️"),
            Mission(id: "c4m5", title: "Stuck Tummy", scene: "🚽😖",
                    situation: "With all the indoor days and fried pakoras, {name}'s tummy feels stuck and uncomfy.",
                    kind: .remedy(.stuckTummy), stuckMood: .sick,
                    successText: "Ahh, much better! {name}'s tummy is back on track.", successEmoji: "🌀"),
        ]),

        Chapter(id: "c5", number: 5, title: "The Great Science Fair", emoji: "🔬",
                intro: "{name} is building a volcano for the Science Fair!", tint: 4, missions: [
            Mission(id: "c5m1", title: "Butterflies in the Tummy", scene: "🦋🌙",
                    situation: "It's the night before. {name} is so nervous, sleep just won't come.",
                    kind: .meal(needs: [.calm], avoid: nil), stuckMood: .worried,
                    successText: "Calm and cosy, {name} drifts off to sleep.", successEmoji: "🌙"),
            Mission(id: "c5m2", title: "Steady Hands", scene: "🌋🧪",
                    situation: "Mixing the volcano potion needs exact spoonfuls and steady hands.",
                    kind: .meal(needs: [.focus, .strength], avoid: nil), stuckMood: .worried,
                    successText: "Measured perfectly. The volcano is ready!", successEmoji: "🌋"),
            Mission(id: "c5w1", title: "The Rising Batter Experiment", scene: "🔬🫧",
                    situation: "For extra credit, {name} studies the batter jar in {elder}'s kitchen. Last night it was flat. This morning it has puffed up!",
                    kind: .wisdom(.fermenting), stuckMood: .worried,
                    successText: "{name} adds 'Fermentation' to the science poster. The judges love it!", successEmoji: "🧪"),
            Mission(id: "c5w2", title: "The Vitamin A Mystery", scene: "🥕📖",
                    situation: "{name}'s science book says carrots have vitamin A. But {elder} says carrots need a friend to make it work.",
                    kind: .wisdom(.fatForVitaminA), stuckMood: .worried,
                    successText: "Mystery solved! {name} explains how vitamin A dissolves in fat.", successEmoji: "🔎"),
            Mission(id: "c5m3", title: "Thumpy Head", scene: "🤕🏃",
                    situation: "Rushing around all morning and forgetting to drink water, {name}'s head starts to thump.",
                    kind: .remedy(.mildHeadache), stuckMood: .sick,
                    successText: "Head clear! {name} remembers: water and rest help the brain.", successEmoji: "💧"),
            Mission(id: "c5m4", title: "Presentation Time", scene: "🎤👩‍🏫",
                    situation: "The judges are here! {name} needs energy to talk, focus to remember, and a calm voice.",
                    kind: .meal(needs: [.energy, .focus, .calm], avoid: nil), stuckMood: .worried,
                    successText: "WHOOSH! The volcano erupts and {name} explains it perfectly. First prize!", successEmoji: "🏆"),
        ]),

        Chapter(id: "c6", number: 6, title: "Friends & Allergies", emoji: "🎉",
                intro: "It's party season! Tiffy teaches {name} to look after friends, too.", tint: 5, missions: [
            Mission(id: "c6m1", title: "Zoya's Peanut Allergy", scene: "🎈🥜",
                    situation: "{name} is packing snacks for a picnic with Zoya, who is allergic to peanuts. Pick tasty energy food with NO peanuts.",
                    kind: .meal(needs: [.energy, .immunity], avoid: .peanuts), stuckMood: .worried,
                    successText: "Zoya and {name} share a safe, happy picnic. Good friends check for allergies!", successEmoji: "🧺"),
            Mission(id: "c6m2", title: "Pollen Sneezes", scene: "🌼🤧",
                    situation: "Spring flowers are blooming, and pollen is making {name} sneeze again and again.",
                    kind: .remedy(.sneezyAllergy), stuckMood: .sick,
                    successText: "Fewer sneezes! And {name} tells a grown-up, so a doctor can help too.", successEmoji: "🌷"),
            Mission(id: "c6m3", title: "Dance-Off!", scene: "💃🕺",
                    situation: "Aarav's birthday party has a dance-off! {name} needs bendy moves and energy to keep dancing.",
                    kind: .meal(needs: [.energy, .flexibility, .hydration], avoid: nil), stuckMood: .tired,
                    successText: "Spin, jump, groove! {name} dances till the last song.", successEmoji: "🪩"),
            Mission(id: "c6w1", title: "Planning the Party Plate", scene: "🎉🍽️",
                    situation: "{name} and {elder} are planning food for a get-together. Which plate is a proper meal?",
                    kind: .wisdom(.balancedPlate), stuckMood: .worried,
                    successText: "The party plate has a little of everything, and everyone goes home happy.", successEmoji: "🍽️"),
            Mission(id: "c6m4", title: "Ishaan Can't Have Milk", scene: "🥛🚫",
                    situation: "Ishaan is coming over and is allergic to dairy. Make a strong-bones snack for both of you with NO milk.",
                    kind: .meal(needs: [.bones, .strength], avoid: .dairy), stuckMood: .worried,
                    successText: "Calcium without milk! Ishaan and {name} build a giant block tower.", successEmoji: "🧱"),
            Mission(id: "c6m5", title: "Party Tummy", scene: "🎂🤢",
                    situation: "Cake, chips and cola at the party, and now {name}'s tummy is grumbling.",
                    kind: .remedy(.tummyAche), stuckMood: .sick,
                    successText: "Tummy calm again. {name} learns: party food is a sometimes food!", successEmoji: "🌀"),
            Mission(id: "c6w2", title: "After the Feast", scene: "🌿😋",
                    situation: "The feast is over and everyone is very full. {elder} reaches for something to share.",
                    kind: .wisdom(.afterMeal), stuckMood: .worried,
                    successText: "Fresh breath and settled tummies all round!", successEmoji: "🌿"),
        ]),

        Chapter(id: "c7", number: 7, title: "Winter Camp in the Hills", emoji: "🏕️",
                intro: "A school trip to the mountains! Tents, trails and campfires.", tint: 6, missions: [
            Mission(id: "c7m1", title: "The Frosty Trail", scene: "🏔️❄️",
                    situation: "The morning hike is long and cold. {name} needs to keep going and keep germs away.",
                    kind: .meal(needs: [.stamina, .immunity], avoid: nil), stuckMood: .tired,
                    successText: "Step by step, {name} reaches the top and sees the snowy peaks!", successEmoji: "🏔️"),
            Mission(id: "c7w1", title: "Cold Camp Dinner", scene: "❄️🍲",
                    situation: "It's freezing at camp! {elder} packed a recipe card in Tiffy for cold nights.",
                    kind: .wisdom(.winterWarmer), stuckMood: .worried,
                    successText: "Warm and cosy, {name} is ready for the night.", successEmoji: "🔥"),
            Mission(id: "c7m2", title: "Pitching the Tent", scene: "⛺️🔨",
                    situation: "Pull the ropes, hammer the pegs, read the instructions. Tent building is hard work!",
                    kind: .meal(needs: [.strength, .focus], avoid: nil), stuckMood: .worried,
                    successText: "The tent is up, and it's the straightest one in camp!", successEmoji: "⛺️"),
            Mission(id: "c7m3", title: "Giggle Hiccups", scene: "😂😲",
                    situation: "{name} laughed so hard at a joke that the hiccups won't stop. Hic! Hic!",
                    kind: .remedy(.hiccups), stuckMood: .worried,
                    successText: "Hiccups gone! Time for more (careful) laughing.", successEmoji: "😄"),
            Mission(id: "c7m4", title: "The Climbing Wall", scene: "🧗🪨",
                    situation: "The climbing wall is tall! {name} needs strong bones, strong arms and bendy legs.",
                    kind: .meal(needs: [.bones, .strength, .flexibility], avoid: nil), stuckMood: .worried,
                    successText: "Ring the bell at the top! {name} climbed the whole wall!", successEmoji: "🔔"),
            Mission(id: "c7w2", title: "Stars After Dinner", scene: "🚶🌌",
                    situation: "Dinner is done. {name} wants to jump straight into the sleeping bag, but {elder}'s voice echoes from Tiffy...",
                    kind: .wisdom(.afterDinnerWalk), stuckMood: .worried,
                    successText: "A slow walk under the stars, and {name} spots three shooting stars!", successEmoji: "🌠"),
            Mission(id: "c7m5", title: "Campfire Calm", scene: "🔥🌌",
                    situation: "After the big day, {name} is buzzing with excitement and can't settle down for campfire stories.",
                    kind: .meal(needs: [.calm, .tummy], avoid: nil), stuckMood: .tired,
                    successText: "Under the stars, {name} listens to stories and falls happily asleep. What a year!", successEmoji: "🌌"),
        ]),
        Chapter(id: "c8", number: 8, title: "Grandparents' Day", emoji: "👵🏽",
                intro: "It's Grandparents' Day at school! {name} wants to bring the family's food wisdom to class.", tint: 1, missions: [
            Mission(id: "c8m1", title: "Interview: The Best Remedy", scene: "🎙️👵🏽",
                    situation: "Teacher says: 'Bring one piece of wisdom from home.' Tiffy says the best place to start is with a grandparent.",
                    kind: .askElder(question: WisdomContent.elderQuestions[7]), stuckMood: .happy,
                    successText: "The remedy story is saved. Now it lives in the Wisdom Book!", successEmoji: "📜"),
            Mission(id: "c8m2", title: "Interview: Summer and Winter Food", scene: "🎙️👵🏽",
                    situation: "Next question for the class project! Find a grandparent, parent or elder and ask them this.",
                    kind: .askElder(question: WisdomContent.elderQuestions[3]), stuckMood: .happy,
                    successText: "Another family secret saved for the class project!", successEmoji: "📜"),
            Mission(id: "c8m3", title: "Cooking for the Whole Family", scene: "👩‍🍳🍲",
                    situation: "{name} is helping cook a big lunch for Grandparents' Day: chopping, stirring and staying calm in a busy kitchen.",
                    kind: .meal(needs: [.energy, .focus, .calm], avoid: nil), stuckMood: .tired,
                    successText: "The lunch is ready, and it's made from family recipes!", successEmoji: "🍲"),
            Mission(id: "c8m4", title: "Interview: What Goes Together", scene: "🎙️👵🏽",
                    situation: "Last question! This one is about combinations: which foods are friends, and which are not.",
                    kind: .askElder(question: WisdomContent.elderQuestions[4]), stuckMood: .happy,
                    successText: "{name} has a whole notebook of family food wisdom now.", successEmoji: "📜"),
            Mission(id: "c8m5", title: "The Grandparents' Day Speech", scene: "🎤👵🏽👴🏽",
                    situation: "It's time to stand up and tell the class everything the family taught. {name}'s knees are a little wobbly.",
                    kind: .meal(needs: [.focus, .calm], avoid: nil), stuckMood: .worried,
                    successText: "{name} shares the family's wisdom, and every grandparent in the room is smiling. Tiffy whispers: 'Now YOU carry the recipes too.'", successEmoji: "💛"),
        ]),
    ]

    static var allMissions: [Mission] { chapters.flatMap(\.missions) }

    static let hints: [String] = [
        "Tap a food to put it on the plate. Tap ⓘ to see what's inside!",
        "Look at the superpowers each food gives, and match what {name} needs.",
        "Sometimes foods are yummy, but they won't help in a tricky spot.",
        "Grandma recipes are full of tiny helpers called micronutrients!",
    ]
}
