import Foundation

/// "Tiffin Tales": {name} and Tiffy, a talking steel tiffin box from Dadi's
/// kitchen, go through one big year of small adventures. Each mission is a
/// bite-sized tricky spot that the right food or home remedy fixes.
enum StoryContent {
    static let companionName = "Tiffy"

    static let prologue = """
    On {name}'s birthday, Dadi gave a very special present: a shiny steel tiffin box. \
    When {name} opened the lid, it giggled! "Hello! I'm Tiffy. I carry the recipes of \
    every grandma in the world. Whenever you're stuck, open me up, and together we'll \
    find the food that helps!"
    """

    static let chapters: [Chapter] = [
        Chapter(id: "c1", number: 1, title: "The Sleepy Monday", emoji: "🏫",
                intro: "A brand new school week! But Monday has a few surprises.", tint: 0, missions: [
            Mission(id: "c1m1", title: "Can't Get Out of Bed", scene: "🛏️⏰",
                    situation: "The alarm is ringing, but {name} feels like a floppy noodle. The school bus comes in 20 minutes!",
                    kind: .meal(needs: [.energy, .stamina], avoid: nil), stuckMood: .sleepy,
                    successText: "{name} jumps out of bed, brushes, and catches the bus with a big wave!", successEmoji: "🚌"),
            Mission(id: "c1m2", title: "The Spelling Bee", scene: "🐝📝",
                    situation: "Ms. Rao calls out 'ELEPHANT'. {name}'s brain feels foggy, and the letters are jumbling up!",
                    kind: .meal(needs: [.focus], avoid: nil), stuckMood: .worried,
                    successText: "E-L-E-P-H-A-N-T! {name} spells it perfectly. The class claps!", successEmoji: "🏅"),
            Mission(id: "c1m3", title: "The Heavy Library Books", scene: "📚📚",
                    situation: "It's {name}'s turn to carry the class library books. The pile is so heavy, arms are wobbling!",
                    kind: .meal(needs: [.strength, .bones], avoid: nil), stuckMood: .tired,
                    successText: "{name} carries the whole pile to the library without a wobble.", successEmoji: "💪"),
            Mission(id: "c1m4", title: "Scratchy Throat", scene: "🧊🥤",
                    situation: "After an icy drink at recess, {name}'s throat feels scratchy and it hurts to talk.",
                    kind: .remedy(.soreThroat), stuckMood: .sick,
                    successText: "The throat feels soothed. {name} can sing in music class again!", successEmoji: "🎵"),
        ]),

        Chapter(id: "c2", number: 2, title: "Sports Day Surprise", emoji: "🏃",
                intro: "Sports Day is in one week, and {name} is in the relay team!", tint: 1, missions: [
            Mission(id: "c2m1", title: "Huffing After One Lap", scene: "🏟️💨",
                    situation: "Coach blows the whistle. After just one lap, {name} is huffing and puffing.",
                    kind: .meal(needs: [.stamina, .energy], avoid: nil), stuckMood: .tired,
                    successText: "{name} runs three whole laps and still has breath to cheer!", successEmoji: "🏃"),
            Mission(id: "c2m2", title: "Stiff as a Stick", scene: "🧘🤸",
                    situation: "Yoga warm-ups! But {name} can't touch toes; legs feel stiff as a stick.",
                    kind: .meal(needs: [.flexibility, .hydration], avoid: nil), stuckMood: .worried,
                    successText: "Stretch, bend, touch! {name} does a perfect butterfly pose.", successEmoji: "🦋"),
            Mission(id: "c2m3", title: "Hot Afternoon Practice", scene: "☀️🥵",
                    situation: "The sun is blazing. {name} feels dizzy and droopy in the middle of practice.",
                    kind: .remedy(.tooHot), stuckMood: .sick,
                    successText: "Cool and refreshed, {name} is ready to practice again, in the shade!", successEmoji: "⛱️"),
            Mission(id: "c2m4", title: "Sore Legs Morning", scene: "🦵😖",
                    situation: "The day after practice, {name}'s legs ache with every step down the stairs.",
                    kind: .remedy(.tiredMuscles), stuckMood: .tired,
                    successText: "The legs feel loose and happy again. Muscles grow stronger with rest!", successEmoji: "🌟"),
            Mission(id: "c2m5", title: "The Relay Final", scene: "🏁🥇",
                    situation: "It's the final race! {name} has to run fast AND catch the baton without dropping it.",
                    kind: .meal(needs: [.stamina, .strength, .focus], avoid: nil), stuckMood: .worried,
                    successText: "Catch, zoom, finish! {name}'s team wins the relay!", successEmoji: "🥇"),
        ]),

        Chapter(id: "c3", number: 3, title: "Holidays at Nani's Village", emoji: "🌾",
                intro: "Summer holidays! {name} and Tiffy are off to Nani's village.", tint: 2, missions: [
            Mission(id: "c3m1", title: "Wobbly Train Ride", scene: "🚂🌀",
                    situation: "The train rocks side to side, and {name}'s tummy is wobbling with it.",
                    kind: .remedy(.travelTummy), stuckMood: .sick,
                    successText: "Tummy settled, {name} counts cows and fields out of the window.", successEmoji: "🐄"),
            Mission(id: "c3m2", title: "Helping in the Garden", scene: "🪴🪣",
                    situation: "Nani needs help carrying water buckets and bending to plant seeds.",
                    kind: .meal(needs: [.strength, .flexibility], avoid: nil), stuckMood: .tired,
                    successText: "Bucket by bucket, seed by seed. The whole garden is planted!", successEmoji: "🌱"),
            Mission(id: "c3m3", title: "Mosquito Party", scene: "🦟🌙",
                    situation: "Evening in the courtyard, and a mosquito bit {name}'s arm. It is SO itchy!",
                    kind: .remedy(.itchyBite), stuckMood: .worried,
                    successText: "The itch calms down. Tonight {name} sleeps under the mosquito net!", successEmoji: "🕸️"),
            Mission(id: "c3m4", title: "Too Many Laddoos", scene: "🍬🦷",
                    situation: "After the village fair and lots of sweets, one of {name}'s teeth starts to ache.",
                    kind: .remedy(.toothache), stuckMood: .sick,
                    successText: "The ache calms down. {name} promises to brush twice a day, and Nani books a dentist visit.", successEmoji: "🪥"),
            Mission(id: "c3m5", title: "Nani's Cooking Lesson", scene: "👵🏽🍳",
                    situation: "Nani is teaching {name} a family recipe. It needs careful measuring and a steady, calm mind.",
                    kind: .meal(needs: [.focus, .calm], avoid: nil), stuckMood: .worried,
                    successText: "Perfectly measured! Nani says {name} cooks just like she did as a child.", successEmoji: "🥘"),
        ]),

        Chapter(id: "c4", number: 4, title: "Monsoon Mysteries", emoji: "🌧️",
                intro: "The rains are here! Puddles, paper boats and a few sniffles.", tint: 3, missions: [
            Mission(id: "c4m1", title: "Rainy Day Sniffles", scene: "☔️🤧",
                    situation: "Splash! {name} got soaked in the rain, and now the nose won't stop dripping.",
                    kind: .remedy(.sniffles), stuckMood: .sick,
                    successText: "Nose clear, {name} can smell the wet earth again!", successEmoji: "🌈"),
            Mission(id: "c4m2", title: "Germ Shield Up!", scene: "🦠🛡️",
                    situation: "Half the class is sneezing. {name} needs a germ shield to stay well this week.",
                    kind: .meal(needs: [.immunity, .tummy], avoid: nil), stuckMood: .worried,
                    successText: "Shield up! {name} stays healthy all week long.", successEmoji: "🛡️"),
            Mission(id: "c4m3", title: "Coughing at Night", scene: "🌙😮‍💨",
                    situation: "It's bedtime, but a tickly cough keeps waking {name} up.",
                    kind: .remedy(.cough), stuckMood: .sick,
                    successText: "The cough quiets down, and {name} sleeps through the night.", successEmoji: "😴"),
            Mission(id: "c4m4", title: "Paper Boat Fleet", scene: "⛵️📄",
                    situation: "{name} wants to fold 10 paper boats for the puddle race. Folding needs patient, careful fingers.",
                    kind: .meal(needs: [.focus, .calm], avoid: nil), stuckMood: .worried,
                    successText: "Ten perfect boats sail down the puddle river!", successEmoji: "⛵️"),
            Mission(id: "c4m5", title: "Stuck Tummy", scene: "🚽😖",
                    situation: "With all the indoor days and fried pakoras, {name}'s tummy feels stuck and uncomfy.",
                    kind: .remedy(.stuckTummy), stuckMood: .sick,
                    successText: "Ahh, much better! {name}'s tummy is back on track.", successEmoji: "🌀"),
        ]),

        Chapter(id: "c5", number: 5, title: "The Great Science Fair", emoji: "🔬",
                intro: "{name} is building a volcano for the Science Fair!", tint: 4, missions: [
            Mission(id: "c5m1", title: "Butterflies in the Tummy", scene: "🦋🌙",
                    situation: "It's the night before. {name} is so nervous, sleep just won't come.",
                    kind: .meal(needs: [.calm], avoid: nil), stuckMood: .worried,
                    successText: "Calm and cosy, {name} drifts off to sleep.", successEmoji: "🌙"),
            Mission(id: "c5m2", title: "Steady Hands", scene: "🌋🧪",
                    situation: "Mixing the volcano potion needs exact spoonfuls and steady hands.",
                    kind: .meal(needs: [.focus, .strength], avoid: nil), stuckMood: .worried,
                    successText: "Measured perfectly. The volcano is ready!", successEmoji: "🌋"),
            Mission(id: "c5m3", title: "Thumpy Head", scene: "🤕🏃",
                    situation: "Rushing around all morning and forgetting to drink water, {name}'s head starts to thump.",
                    kind: .remedy(.mildHeadache), stuckMood: .sick,
                    successText: "Head clear! {name} remembers: water and rest help the brain.", successEmoji: "💧"),
            Mission(id: "c5m4", title: "Presentation Time", scene: "🎤👩‍🏫",
                    situation: "The judges are here! {name} needs energy to talk, focus to remember, and a calm voice.",
                    kind: .meal(needs: [.energy, .focus, .calm], avoid: nil), stuckMood: .worried,
                    successText: "WHOOSH! The volcano erupts and {name} explains it perfectly. First prize!", successEmoji: "🏆"),
        ]),

        Chapter(id: "c6", number: 6, title: "Friends & Allergies", emoji: "🎉",
                intro: "It's party season! Tiffy teaches {name} to look after friends, too.", tint: 5, missions: [
            Mission(id: "c6m1", title: "Zoya's Peanut Allergy", scene: "🎈🥜",
                    situation: "{name} is packing snacks for a picnic with Zoya, who is allergic to peanuts. Pick tasty energy food with NO peanuts.",
                    kind: .meal(needs: [.energy, .immunity], avoid: .peanuts), stuckMood: .worried,
                    successText: "Zoya and {name} share a safe, happy picnic. Good friends check for allergies!", successEmoji: "🧺"),
            Mission(id: "c6m2", title: "Pollen Sneezes", scene: "🌼🤧",
                    situation: "Spring flowers are blooming, and pollen is making {name} sneeze again and again.",
                    kind: .remedy(.sneezyAllergy), stuckMood: .sick,
                    successText: "Fewer sneezes! And {name} tells a grown-up, so a doctor can help too.", successEmoji: "🌷"),
            Mission(id: "c6m3", title: "Dance-Off!", scene: "💃🕺",
                    situation: "Aarav's birthday party has a dance-off! {name} needs bendy moves and energy to keep dancing.",
                    kind: .meal(needs: [.energy, .flexibility, .hydration], avoid: nil), stuckMood: .tired,
                    successText: "Spin, jump, groove! {name} dances till the last song.", successEmoji: "🪩"),
            Mission(id: "c6m4", title: "Ishaan Can't Have Milk", scene: "🥛🚫",
                    situation: "Ishaan is coming over and is allergic to dairy. Make a strong-bones snack for both of you with NO milk.",
                    kind: .meal(needs: [.bones, .strength], avoid: .dairy), stuckMood: .worried,
                    successText: "Calcium without milk! Ishaan and {name} build a giant block tower.", successEmoji: "🧱"),
            Mission(id: "c6m5", title: "Party Tummy", scene: "🎂🤢",
                    situation: "Cake, chips and cola at the party, and now {name}'s tummy is grumbling.",
                    kind: .remedy(.tummyAche), stuckMood: .sick,
                    successText: "Tummy calm again. {name} learns: party food is a sometimes food!", successEmoji: "🌀"),
        ]),

        Chapter(id: "c7", number: 7, title: "Winter Camp in the Hills", emoji: "🏕️",
                intro: "A school trip to the mountains! Tents, trails and campfires.", tint: 6, missions: [
            Mission(id: "c7m1", title: "The Frosty Trail", scene: "🏔️❄️",
                    situation: "The morning hike is long and cold. {name} needs to keep going and keep germs away.",
                    kind: .meal(needs: [.stamina, .immunity], avoid: nil), stuckMood: .tired,
                    successText: "Step by step, {name} reaches the top and sees the snowy peaks!", successEmoji: "🏔️"),
            Mission(id: "c7m2", title: "Pitching the Tent", scene: "⛺️🔨",
                    situation: "Pull the ropes, hammer the pegs, read the instructions. Tent building is hard work!",
                    kind: .meal(needs: [.strength, .focus], avoid: nil), stuckMood: .worried,
                    successText: "The tent is up, and it's the straightest one in camp!", successEmoji: "⛺️"),
            Mission(id: "c7m3", title: "Giggle Hiccups", scene: "😂😲",
                    situation: "{name} laughed so hard at a joke that the hiccups won't stop. Hic! Hic!",
                    kind: .remedy(.hiccups), stuckMood: .worried,
                    successText: "Hiccups gone! Time for more (careful) laughing.", successEmoji: "😄"),
            Mission(id: "c7m4", title: "The Climbing Wall", scene: "🧗🪨",
                    situation: "The climbing wall is tall! {name} needs strong bones, strong arms and bendy legs.",
                    kind: .meal(needs: [.bones, .strength, .flexibility], avoid: nil), stuckMood: .worried,
                    successText: "Ring the bell at the top! {name} climbed the whole wall!", successEmoji: "🔔"),
            Mission(id: "c7m5", title: "Campfire Calm", scene: "🔥🌌",
                    situation: "After the big day, {name} is buzzing with excitement and can't settle down for campfire stories.",
                    kind: .meal(needs: [.calm, .tummy], avoid: nil), stuckMood: .tired,
                    successText: "Under the stars, {name} listens to stories and falls happily asleep. What a year!", successEmoji: "🌌"),
        ]),
    ]

    static var allMissions: [Mission] { chapters.flatMap(\.missions) }

    static let hints: [String] = [
        "Tap a food to put it on the plate. Tap ⓘ to see what's inside!",
        "Look at the superpowers each food gives, and match what {name} needs.",
        "Sometimes foods are yummy, but they won't help in a tricky spot.",
        "Grandma recipes are full of tiny helpers called micronutrients!",
    ]
}
