import Foundation

/// Grandparent food knowledge: pairings, kitchen magic, seasons and habits.
/// Each card pairs "Dadi says" (the tradition) with "Science says" (what
/// researchers have found), and is honest when science hasn't caught up yet.
enum WisdomContent {
    static let all: [Wisdom] = pairings + preparation + seasons + habits

    // MARK: What goes with what

    static let pairings: [Wisdom] = [
        Wisdom("dal-chawal", .grainPartner, .pairing, "Dal's Best Friend", "🍛",
               origin: "Homes across India",
               question: "{elder} says dal is only half a superhero. What is its best partner?",
               answer: WisdomChoice("🍚", "Rice or roti", "Dal + a grain = a complete protein!"),
               distractors: [WisdomChoice("🍟", "Chips", "Chips are a sometimes food with almost no protein."),
                             WisdomChoice("🥤", "Cola", "Cola is just sugar water."),
                             WisdomChoice("🍰", "Cake", "Cake is a treat, not a partner for dal.")],
               grandma: "Dal-chawal, dal-roti, khichdi: every grandma serves dal together with a grain.",
               science: "Protein is built from little blocks called amino acids. Dals are low in one block and grains are low in another. Together they make a complete protein!",
               evidence: .strong),
        Wisdom("idli-sambar", .grainPartner, .pairing, "Idli Loves Sambar", "⚪️",
               cultures: ["tamil", "kannada", "kerala", "andhra"], origin: "South Indian homes",
               question: "Soft idlis are ready! What does {elder} always serve with them?",
               answer: WisdomChoice("🍲", "Sambar with dal and vegetables", "Rice idli + dal sambar = complete protein, plus veggies!"),
               distractors: [WisdomChoice("🍬", "Sugar syrup", "Too sweet, and no protein."),
                             WisdomChoice("🥤", "A fizzy drink", "Fizzy drinks don't help at all."),
                             WisdomChoice("🍟", "French fries", "That's a fried sometimes food.")],
               grandma: "Idli, dosa and pongal are never served alone: there's always sambar or chutney.",
               science: "Idli's rice and urad dal plus sambar's toor dal give all the protein building blocks, and fermenting the batter adds B vitamins.",
               evidence: .strong),
        Wisdom("saag-makki", .grainPartner, .pairing, "Saag Needs Makki", "🌽",
               cultures: ["punjabi"], origin: "Punjabi homes",
               question: "Sarson da saag is bubbling on the stove. What goes with it?",
               answer: WisdomChoice("🫓", "Makki di roti with a little gur", "Greens + maize + jaggery: a winter power plate!"),
               distractors: [WisdomChoice("🍞", "White bread", "Makki roti has more fiber."),
                             WisdomChoice("🍦", "Ice cream", "Not on a cold winter day!"),
                             WisdomChoice("🍜", "Instant noodles", "That's a sometimes food.")],
               grandma: "In Punjabi winters, saag comes with makki di roti, white butter and a piece of gur.",
               science: "Mustard greens bring iron, calcium and vitamins A and C; maize brings energy, and a little fat helps your body absorb vitamin A.",
               evidence: .some, allergens: [.dairy], diet: .vegetarian),
        Wisdom("frijoles-tortilla", .grainPartner, .pairing, "Beans + Corn", "🌮",
               cultures: ["mexican"], origin: "Mexican homes",
               question: "Abuela made frijoles de olla. What does she serve them with?",
               answer: WisdomChoice("🫓", "Warm corn tortillas", "Beans + corn = complete protein, a pair thousands of years old!"),
               distractors: [WisdomChoice("🍬", "Candy", "No protein there."),
                             WisdomChoice("🥤", "Soda", "Just sugar."),
                             WisdomChoice("🍩", "A donut", "A sometimes food.")],
               grandma: "In Mexico, beans, corn and squash have grown together in the milpa field for thousands of years. They're the 'three sisters'.",
               science: "Beans and corn complete each other's protein. Corn soaked in lime (nixtamal) also releases vitamin B3 and adds calcium.",
               evidence: .strong),
        Wisdom("hummus-pita", .grainPartner, .pairing, "Chickpeas + Bread", "🧆",
               cultures: ["levantine"], origin: "Middle Eastern homes",
               question: "Teta (grandma) put out a bowl of hummus. What do we scoop it with?",
               answer: WisdomChoice("🫓", "Warm pita bread", "Chickpeas + wheat = complete protein."),
               distractors: [WisdomChoice("🍪", "Cookies", "Too sweet."),
                             WisdomChoice("🍬", "Candy", "No."),
                             WisdomChoice("🥤", "Soda", "No.")],
               grandma: "Mezze is meant to be shared: hummus, bread, salad and olives together.",
               science: "Chickpeas and wheat together give all the protein building blocks, and tahini adds calcium.",
               evidence: .strong, allergens: [.sesame, .gluten]),
        Wisdom("injera-wat", .grainPartner, .pairing, "Injera + Lentils", "🫓",
               cultures: ["ethiopian"], origin: "Ethiopian homes",
               question: "Grandma spreads injera on the big plate. What goes on top?",
               answer: WisdomChoice("🍲", "Misir wat (lentil stew)", "Teff + lentils = complete protein with lots of iron!"),
               distractors: [WisdomChoice("🍬", "Candy", "No."),
                             WisdomChoice("🍟", "Chips", "No."),
                             WisdomChoice("🥤", "Soda", "No.")],
               grandma: "Families eat from one big plate, tearing injera to scoop up stews together.",
               science: "Teff is a tiny grain full of iron and calcium; with lentils it makes a complete protein.",
               evidence: .strong),
        Wisdom("waakye", .grainPartner, .pairing, "Rice + Beans", "🍚",
               cultures: ["west-african"], origin: "Ghanaian homes",
               question: "Grandma is making waakye. What two things cook together in the pot?",
               answer: WisdomChoice("🫘", "Rice and beans", "Together they make a complete protein."),
               distractors: [WisdomChoice("🍬", "Rice and sugar", "That's a sweet, not a meal."),
                             WisdomChoice("🍟", "Chips and salt", "No."),
                             WisdomChoice("🧊", "Rice and ice", "Brrr!")],
               grandma: "Waakye is rice and black-eyed beans cooked together, a favourite breakfast in Ghana.",
               science: "Beans plus rice gives all the protein building blocks your muscles need.",
               evidence: .strong),
        Wisdom("rice-miso", .grainPartner, .pairing, "Rice + Miso", "🍙",
               cultures: ["japanese"], origin: "Japanese homes",
               question: "Obaachan (grandma) serves a bowl of rice. What soup comes with it?",
               answer: WisdomChoice("🍵", "Miso soup with tofu", "Rice + soy = complete protein, plus good bacteria."),
               distractors: [WisdomChoice("🥤", "Soda", "No."),
                             WisdomChoice("🍬", "Candy", "No."),
                             WisdomChoice("🍩", "A donut", "No.")],
               grandma: "Every Japanese home meal has rice and soup together.",
               science: "Soybeans in miso and tofu complete rice's protein, and fermented miso has friendly bacteria.",
               evidence: .strong, allergens: [.soy]),

        Wisdom("lemon-dal", .ironHelper, .pairing, "Lemon Unlocks Iron", "🍋",
               origin: "Homes across India",
               question: "Palak dal is full of iron, but iron is shy! What does {elder} squeeze on top to help {name}'s body take it in?",
               answer: WisdomChoice("🍋", "A squeeze of lemon", "Vitamin C helps your body absorb plant iron!"),
               distractors: [WisdomChoice("🍵", "A cup of tea with the meal", "Tea actually makes iron harder to absorb. Have it later!"),
                             WisdomChoice("🍬", "Sugar", "Sugar doesn't help iron."),
                             WisdomChoice("🧂", "Lots of extra salt", "Too much salt isn't good for you.")],
               grandma: "A squeeze of nimbu on dal, chole and sprouts, and amla or guava with meals.",
               science: "Iron from plants is hard for the body to absorb. Vitamin C from lemon, amla, guava or tomato can help the body take in much more of it.",
               evidence: .strong),
        Wisdom("lime-beans", .ironHelper, .pairing, "Lime on Beans", "🍋",
               cultures: ["mexican"], origin: "Mexican homes",
               question: "Abuela adds something sour to the frijoles and salsa. What is it?",
               answer: WisdomChoice("🍋", "A squeeze of lime", "Vitamin C helps your body absorb the iron in beans."),
               distractors: [WisdomChoice("🥤", "Soda", "No."),
                             WisdomChoice("🍬", "Sugar", "No."),
                             WisdomChoice("🧈", "Lots of butter", "Not this time.")],
               grandma: "Limón goes on almost everything: beans, soups, fruit and corn.",
               science: "Vitamin C in lime and tomato salsa helps the body absorb the iron in beans.",
               evidence: .strong),
        Wisdom("lemon-lentil-soup", .ironHelper, .pairing, "Lemon in Lentil Soup", "🍋",
               cultures: ["levantine"], origin: "Middle Eastern homes",
               question: "Shorbat adas (lentil soup) is ready. What does Teta squeeze on top?",
               answer: WisdomChoice("🍋", "Fresh lemon", "Vitamin C helps the iron from lentils work."),
               distractors: [WisdomChoice("🍬", "Sugar", "No."),
                             WisdomChoice("🍵", "Strong tea in the soup", "Tea blocks iron."),
                             WisdomChoice("🧊", "Ice cubes", "No.")],
               grandma: "Lentil soup is always served with a lemon wedge.",
               science: "Vitamin C turns plant iron into a form your body absorbs much more easily.",
               evidence: .strong),

        Wisdom("haldi-mirch", .haldiPepper, .pairing, "Haldi's Tiny Friend", "🟠",
               origin: "Homes across India",
               question: "{elder} puts haldi in the dal tadka. Which tiny friend helps the haldi work better?",
               answer: WisdomChoice("⚫️", "A pinch of black pepper", "Pepper helps your body absorb haldi's curcumin many times better!"),
               distractors: [WisdomChoice("🍬", "Sugar", "Sugar doesn't help."),
                             WisdomChoice("🧊", "Ice", "Cold doesn't help."),
                             WisdomChoice("🥤", "Cola", "No.")],
               grandma: "Haldi and kali mirch go together in dal, sabzi, kadha and haldi doodh.",
               science: "Turmeric's helper, curcumin, is hard for the body to absorb. Piperine from black pepper helps it absorb much more.",
               evidence: .strong),

        Wisdom("hing-rajma", .beansGas, .pairing, "Hing for Happy Tummies", "🟡",
               origin: "Homes across India",
               question: "Rajma for dinner! What does {elder} add to the tadka so tummies don't puff up with gas?",
               answer: WisdomChoice("🟡", "A pinch of hing (and ajwain or jeera)", "These spices help tummies digest beans."),
               distractors: [WisdomChoice("🍬", "A spoon of sugar", "Sugar can make gas worse."),
                             WisdomChoice("🥤", "A fizzy drink", "Fizzy drinks add more bubbles!"),
                             WisdomChoice("🧊", "Ice cubes", "No.")],
               grandma: "Every dal and rajma tadka gets a pinch of hing, and heavy parathas get ajwain.",
               science: "Hing, ajwain and jeera have been studied as digestive helpers. There is some evidence they ease gas, and soaking beans helps too.",
               evidence: .some),
        Wisdom("epazote", .beansGas, .pairing, "Epazote in the Beans", "🌿",
               cultures: ["mexican"], origin: "Mexican homes",
               question: "Abuela drops a green herb into the bean pot. Which one?",
               answer: WisdomChoice("🌿", "Epazote", "A traditional herb to make beans easier to digest."),
               distractors: [WisdomChoice("🍬", "Candy", "No."),
                             WisdomChoice("🧂", "A cup of salt", "Way too much!"),
                             WisdomChoice("🥤", "Soda", "No.")],
               grandma: "Frijoles always get a sprig of epazote for flavour and a calmer tummy.",
               science: "People have used epazote this way for centuries; scientists haven't studied it much yet. Slow cooking and soaking definitely help.",
               evidence: .tradition),

        Wisdom("ghee-carrot", .fatForVitaminA, .pairing, "Vitamin A Needs a Little Fat", "🥕",
               origin: "Homes across India",
               question: "Gajar-matar sabzi has lots of vitamin A. What does {elder} cook it with so the vitamin works?",
               answer: WisdomChoice("🫙", "A spoon of ghee or oil", "Vitamin A dissolves in fat, so a little fat helps you absorb it."),
               distractors: [WisdomChoice("💧", "Boil it in lots of water and throw the water away", "That washes away vitamins!"),
                             WisdomChoice("🍬", "Sugar", "No."),
                             WisdomChoice("🧊", "Freeze it", "No.")],
               grandma: "Sabzi gets a tadka of ghee or oil, and greens get a little makkhan.",
               science: "Vitamins A, D, E and K are fat-soluble. Eating them with a little fat helps your body absorb them.",
               evidence: .strong),
        Wisdom("coconut-thoran", .fatForVitaminA, .pairing, "Coconut in Thoran", "🥥",
               cultures: ["kerala", "tamil"], origin: "Kerala and Tamil homes",
               question: "Ammamma is making a vegetable thoran. What does she always add?",
               answer: WisdomChoice("🥥", "Grated coconut and coconut oil", "The fat helps you absorb the vegetables' vitamins."),
               distractors: [WisdomChoice("🍬", "Sugar", "No."),
                             WisdomChoice("🧊", "Ice", "No."),
                             WisdomChoice("🥤", "Soda", "No.")],
               grandma: "Coconut goes into thoran, avial and chutneys every day.",
               science: "A little fat helps your body take in vitamin A from carrots, beans and greens.",
               evidence: .strong),
    ]

    // MARK: Kitchen magic

    static let preparation: [Wisdom] = [
        Wisdom("soak-rajma", .soaking, .preparation, "Soak Overnight", "💧",
               origin: "Homes across India",
               question: "{elder} puts rajma in a big bowl of water before bed. Why?",
               answer: WisdomChoice("💧", "Soaking makes it soft, quick to cook and easy on the tummy", "Exactly!"),
               distractors: [WisdomChoice("🐟", "To let the beans swim", "Ha! No."),
                             WisdomChoice("🧊", "To keep them cold", "Not the reason."),
                             WisdomChoice("🎨", "To wash off the colour", "Not the reason.")],
               grandma: "Rajma, chana and lobia always soak the night before.",
               science: "Soaking softens beans and lowers phytates, which block minerals like iron and zinc. It also reduces some of the sugars that cause gas.",
               evidence: .strong),
        Wisdom("sprout-moong", .sprouting, .preparation, "Sprouting Power", "🌱",
               origin: "Homes across India",
               question: "How does {elder} make plain moong extra powerful?",
               answer: WisdomChoice("🌱", "Soak it, wrap it in a wet cloth and let it sprout", "Sprouts have more vitamin C and are easier to digest."),
               distractors: [WisdomChoice("🔥", "Fry it in lots of oil", "That adds oil, not power."),
                             WisdomChoice("🍬", "Coat it in sugar", "No."),
                             WisdomChoice("🧊", "Freeze it", "No.")],
               grandma: "Moong, matki and chana are sprouted in a damp cloth for chaat and usal.",
               science: "Sprouting wakes up the seed: vitamin C goes up, and iron and zinc become easier to absorb.",
               evidence: .strong),
        Wisdom("ferment-idli", .fermenting, .preparation, "The Batter Grows Overnight", "🫧",
               origin: "Homes across India",
               question: "Idli batter sits overnight and puffs up. What is happening?",
               answer: WisdomChoice("🫧", "Tiny friendly microbes are fermenting it", "They make it fluffy, easier to digest and add B vitamins."),
               distractors: [WisdomChoice("👻", "A ghost is blowing into it", "Spooky, but no!"),
                             WisdomChoice("🧊", "It is freezing", "No."),
                             WisdomChoice("🧂", "The salt is growing", "No.")],
               grandma: "Batter goes in a warm corner of the kitchen overnight.",
               science: "Fermentation by friendly microbes makes air bubbles, adds B vitamins and makes minerals easier to absorb.",
               evidence: .strong),
        Wisdom("ferment-dhokla", .fermenting, .preparation, "Dhokla Batter Magic", "🧽",
               cultures: ["gujarati"], origin: "Gujarati homes",
               question: "Ba leaves the dhokla batter to rest for hours. Why?",
               answer: WisdomChoice("🫧", "It ferments and gets fluffy", "Fermenting adds B vitamins and makes it spongy!"),
               distractors: [WisdomChoice("😴", "The batter is tired", "Ha! No."),
                             WisdomChoice("🧊", "To make it cold", "No."),
                             WisdomChoice("🍬", "To make it sweet", "No.")],
               grandma: "Khaman, khatta dhokla and handvo batters all rest before steaming.",
               science: "Microbes eat a little of the sugar and make bubbles and B vitamins.",
               evidence: .strong),
        Wisdom("ferment-pakhala", .fermenting, .preparation, "Pakhala Overnight", "🍚",
               cultures: ["odia"], origin: "Odia homes",
               question: "Grandma soaks leftover rice in water overnight for pakhala. What happens to it?",
               answer: WisdomChoice("🫧", "It ferments into a cooling, tummy-friendly meal", "Good bacteria grow, perfect for hot days."),
               distractors: [WisdomChoice("🔥", "It gets hot", "No, it gets cooling!"),
                             WisdomChoice("🍬", "It turns into sugar", "No."),
                             WisdomChoice("🧊", "It freezes", "No.")],
               grandma: "Odisha even celebrates Pakhala Dibasa every March 20th!",
               science: "Fermented rice water has friendly bacteria, and the watery meal helps on hot days.",
               evidence: .some),
        Wisdom("ferment-kimchi", .fermenting, .preparation, "Kimchi Jars", "🥬",
               cultures: ["korean"], origin: "Korean homes",
               question: "Halmeoni packs cabbage with salt and spices into jars for weeks. Why?",
               answer: WisdomChoice("🫧", "To ferment it into kimchi", "Friendly bacteria make it tangy and good for your tummy."),
               distractors: [WisdomChoice("🙈", "To hide it", "No."),
                             WisdomChoice("🍬", "To make candy", "No."),
                             WisdomChoice("🧊", "To freeze it", "No.")],
               grandma: "Families make kimchi together in autumn. It's called kimjang!",
               science: "Lactic-acid bacteria ferment the cabbage, adding tang and good bacteria.",
               evidence: .strong, allergens: [.fish], diet: .nonVegetarian),
        Wisdom("ferment-injera", .fermenting, .preparation, "Injera Bubbles", "🫓",
               cultures: ["ethiopian"], origin: "Ethiopian homes",
               question: "Teff batter sits for days before becoming injera. Why?",
               answer: WisdomChoice("🫧", "It ferments, making it bubbly and tangy", "Fermenting also helps the body use teff's iron."),
               distractors: [WisdomChoice("😴", "It's sleeping", "No."),
                             WisdomChoice("🧊", "To make it cold", "No."),
                             WisdomChoice("🍬", "To make it sweet", "No.")],
               grandma: "A little of the old batter starts the next batch, passed on for years.",
               science: "Fermentation lowers phytates, so minerals like iron are easier to absorb.",
               evidence: .strong),
    ]

    // MARK: Seasons

    static let seasons: [Wisdom] = [
        Wisdom("nimbu-pani", .summerCooler, .season, "Summer Coolers", "🍋",
               origin: "Homes across India",
               question: "It's a blazing summer afternoon. What does {elder} make to cool {name} down?",
               answer: WisdomChoice("🍋", "Nimbu pani with a pinch of salt", "Water + salt + lemon puts back what you sweat out."),
               distractors: [WisdomChoice("☕️", "Hot coffee", "Not for kids, and not cooling!"),
                             WisdomChoice("🥤", "Icy cola", "Lots of sugar. Water drinks are better."),
                             WisdomChoice("🍫", "Hot chocolate", "Too warm and sweet.")],
               grandma: "Summer means cooling foods: nimbu pani, cucumber, watermelon and curd.",
               science: "On hot days you sweat out water and salts. Drinks with water and a pinch of salt put them back.",
               evidence: .strong),
        Wisdom("chaas-summer", .summerCooler, .season, "Chaas After Lunch", "🥛",
               cultures: ["gujarati", "rajasthani", "jain", "punjabi"], origin: "Gujarati, Rajasthani and Punjabi homes",
               question: "Summer lunch is done. What does {elder} pour for everyone?",
               answer: WisdomChoice("🥛", "A glass of masala chaas", "Cooling, salty and full of friendly bacteria."),
               distractors: [WisdomChoice("☕️", "Hot coffee", "Not cooling."),
                             WisdomChoice("🥤", "Cola", "Sugary."),
                             WisdomChoice("🍫", "Hot chocolate", "Too warm.")],
               grandma: "No summer meal ends without chaas with roasted jeera.",
               science: "Buttermilk replaces water and salts and has probiotics for the tummy.",
               evidence: .some, allergens: [.dairy], diet: .vegetarian),
        Wisdom("sattu-summer", .summerCooler, .season, "Sattu Sharbat", "🥤",
               cultures: ["bihari"], origin: "Bihari homes",
               question: "Loo winds are blowing in Bihar. What does Dadi stir up?",
               answer: WisdomChoice("🥤", "Namkeen sattu sharbat", "Protein, water and salt in one glass!"),
               distractors: [WisdomChoice("☕️", "Hot coffee", "No."),
                             WisdomChoice("🥤", "Cola", "No."),
                             WisdomChoice("🍫", "Hot chocolate", "No.")],
               grandma: "Sattu with water, lemon, salt and onion keeps farmers going in the hottest months.",
               science: "Roasted gram gives protein and fiber; the salty water replaces what you sweat out.",
               evidence: .some),
        Wisdom("pakhala-summer", .summerCooler, .season, "Pakhala for Summer", "🍚",
               cultures: ["odia"], origin: "Odia homes",
               question: "It's a scorching day in Odisha. What's for lunch?",
               answer: WisdomChoice("🍚", "Pakhala bhata with badi chura", "Cool fermented rice water: Odisha's summer secret."),
               distractors: [WisdomChoice("🍲", "Very hot, spicy soup", "Not today!"),
                             WisdomChoice("🥤", "Cola", "No."),
                             WisdomChoice("🍫", "Hot chocolate", "No.")],
               grandma: "Pakhala with fried badi, saga and a little lime is the summer lunch.",
               science: "Watery, fermented rice keeps you hydrated and adds friendly bacteria.",
               evidence: .some),
        Wisdom("kokum-summer", .summerCooler, .season, "Kokum Cooler", "🩷",
               cultures: ["maharashtrian"], origin: "Marathi and Konkani homes",
               question: "Aaji has a jar of dark red kokum. What does she make on hot days?",
               answer: WisdomChoice("🩷", "Kokum sharbat or solkadhi", "Cooling and tangy!"),
               distractors: [WisdomChoice("☕️", "Hot coffee", "No."),
                             WisdomChoice("🥤", "Cola", "No."),
                             WisdomChoice("🍫", "Hot chocolate", "No.")],
               grandma: "Konkan summers mean kokum sharbat, and solkadhi after lunch.",
               science: "It's a watery, lightly salted drink that helps replace fluids. Scientists are still studying kokum itself.",
               evidence: .some),
        Wisdom("neer-mor-summer", .summerCooler, .season, "Neer Mor", "🥛",
               cultures: ["tamil", "kerala", "kannada", "andhra"], origin: "South Indian homes",
               question: "During Tamil summers, what do families hand out in clay pots?",
               answer: WisdomChoice("🥛", "Neer mor (thin spiced buttermilk)", "Cooling, salty and good for the tummy."),
               distractors: [WisdomChoice("☕️", "Hot filter coffee", "Not for kids on a hot day."),
                             WisdomChoice("🥤", "Cola", "No."),
                             WisdomChoice("🍫", "Hot chocolate", "No.")],
               grandma: "Families even share neer mor with strangers at temple festivals in summer.",
               science: "Thin buttermilk replaces water and salts and has friendly bacteria.",
               evidence: .some, allergens: [.dairy], diet: .vegetarian),
        Wisdom("agua-fresca", .summerCooler, .season, "Agua Fresca", "🍉",
               cultures: ["mexican"], origin: "Mexican homes",
               question: "It's hot! What does Abuela pour from the big glass jar?",
               answer: WisdomChoice("🍉", "Agua fresca made from fruit and water", "Fruit + water = cool and hydrating."),
               distractors: [WisdomChoice("☕️", "Hot coffee", "No."),
                             WisdomChoice("🍫", "Hot chocolate", "No."),
                             WisdomChoice("🥤", "Cola", "Sugary.")],
               grandma: "Watermelon, cucumber or jamaica agua fresca is always on the table in summer.",
               science: "Watery fruits and drinks keep you hydrated. Less sugar is better!",
               evidence: .strong),
        Wisdom("barley-tea", .summerCooler, .season, "Cold Barley Tea", "🍵",
               cultures: ["japanese", "korean", "chinese"], origin: "Japanese and Korean homes",
               question: "Summer in Japan and Korea. What's in the fridge jug?",
               answer: WisdomChoice("🍵", "Cold barley tea (mugicha / boricha)", "No caffeine, no sugar, just cool and refreshing."),
               distractors: [WisdomChoice("☕️", "Hot coffee", "No."),
                             WisdomChoice("🥤", "Cola", "No."),
                             WisdomChoice("🍫", "Hot chocolate", "No.")],
               grandma: "Every summer fridge has a jug of roasted barley tea.",
               science: "It's mostly water, so it keeps you hydrated without sugar or caffeine.",
               evidence: .strong, allergens: [.gluten]),

        Wisdom("winter-khichdi", .winterWarmer, .season, "Warm Winter Food", "🍲",
               origin: "Homes across India",
               question: "It's a chilly winter evening. What does {elder} cook?",
               answer: WisdomChoice("🍲", "Hot khichdi, soup or dal with ginger", "Warm, cooked food keeps you cosy and full."),
               distractors: [WisdomChoice("🍦", "Ice cream", "Brrr!"),
                             WisdomChoice("🥤", "An icy cold drink", "Not today."),
                             WisdomChoice("🍟", "Chips", "No.")],
               grandma: "Winter brings warm khichdi, soups, ginger, gur and seasonal greens.",
               science: "Warm food doesn't stop colds, but seasonal winter vegetables are full of vitamins, and warm meals keep you comfortable.",
               evidence: .some),
        Wisdom("bajra-gur", .winterWarmer, .season, "Bajra, Gur and Ghee", "🫓",
               cultures: ["rajasthani", "gujarati", "baniya"], origin: "Rajasthani and Gujarati homes",
               question: "Winter morning in the desert. What does {elder} serve?",
               answer: WisdomChoice("🫓", "Bajra roti with gur and ghee", "Millet + jaggery: warm, lasting energy and minerals."),
               distractors: [WisdomChoice("🍦", "Ice cream", "Not in winter!"),
                             WisdomChoice("🥤", "Cold drink", "No."),
                             WisdomChoice("🍬", "Candy", "No.")],
               grandma: "Bajra is a winter grain, and comes with gur, ghee or raab when it's cold.",
               science: "Bajra has iron, magnesium and fiber for long-lasting energy. Jaggery adds a little iron too, but it's still sugar!",
               evidence: .some, allergens: [.dairy], diet: .vegetarian),
        Wisdom("til-gul", .winterWarmer, .season, "Til-Gul on Sankranti", "⚪️",
               cultures: ["maharashtrian", "gujarati"], origin: "Marathi and Gujarati homes",
               question: "It's Makar Sankranti in January. What sweet do families share?",
               answer: WisdomChoice("⚪️", "Til-gul (sesame and jaggery)", "Sesame has calcium and healthy fats for winter."),
               distractors: [WisdomChoice("🍦", "Ice cream", "No."),
                             WisdomChoice("🥤", "Cold drink", "No."),
                             WisdomChoice("🍩", "Donuts", "No.")],
               grandma: "Families share til-gul and say 'Tilgul ghya, god god bola': take til-gul and speak sweetly!",
               science: "Sesame seeds have calcium, iron and healthy fats. Jaggery is still sugar, so a little goes a long way.",
               evidence: .some, saying: "Tilgul ghya, god god bola", allergens: [.sesame]),
        Wisdom("saag-winter", .winterWarmer, .season, "Winter Greens", "🥬",
               cultures: ["punjabi", "kashmiri"], origin: "Punjabi and Kashmiri homes",
               question: "Which greens are best in winter?",
               answer: WisdomChoice("🥬", "Sarson, methi, bathua and haak", "Winter greens are full of iron and vitamins."),
               distractors: [WisdomChoice("🍦", "Ice cream", "No."),
                             WisdomChoice("🍟", "Chips", "No."),
                             WisdomChoice("🥤", "Cold drink", "No.")],
               grandma: "Winter is the season of saag. Every leafy green has its month.",
               science: "Eating vegetables in their season means they're fresh and full of vitamins.",
               evidence: .some),
    ]

    // MARK: Habits

    static let habits: [Wisdom] = [
        Wisdom("saunf-after", .afterMeal, .afterMeal, "Saunf After Meals", "💚",
               origin: "Homes across India",
               question: "The big meal is over. What does {elder} pass around?",
               answer: WisdomChoice("💚", "A pinch of saunf (and mishri)", "Fennel freshens your breath and may help digestion."),
               distractors: [WisdomChoice("🍬", "A big bag of candy", "Sugar sticks to teeth!"),
                             WisdomChoice("🥤", "A fizzy drink", "No."),
                             WisdomChoice("🛌", "Lie down straight away", "Better to sit or walk a little first.")],
               grandma: "Restaurants and homes alike end meals with saunf, sometimes with mishri.",
               science: "Fennel seeds freshen breath, and some studies suggest they ease gas and bloating.",
               evidence: .some),
        Wisdom("mukhwas", .afterMeal, .afterMeal, "Mukhwas Box", "🌸",
               cultures: ["gujarati", "jain", "rajasthani", "sindhi"], origin: "Gujarati and Rajasthani homes",
               question: "After dinner, Ba opens a little box with many sections. What's inside?",
               answer: WisdomChoice("🌸", "Mukhwas: saunf, roasted til and dhana dal", "Seeds to freshen breath and help digestion."),
               distractors: [WisdomChoice("🍬", "Toffees", "Sugar on your teeth."),
                             WisdomChoice("🍟", "Chips", "No."),
                             WisdomChoice("🥤", "Cola", "No.")],
               grandma: "Every Gujarati home has a mukhwas box for after meals.",
               science: "Fennel and coriander seeds may help digestion and freshen breath. There's some evidence for this.",
               evidence: .some, allergens: [.sesame]),
        Wisdom("curd-rice-end", .afterMeal, .afterMeal, "End With Curd Rice", "🍶",
               cultures: ["tamil", "kannada", "andhra"], origin: "South Indian homes",
               question: "A South Indian meal has many courses. Which one comes last?",
               answer: WisdomChoice("🍶", "Curd rice", "Cool and calming, with friendly bacteria for the tummy."),
               distractors: [WisdomChoice("🌶️", "The spiciest dish", "That comes earlier."),
                             WisdomChoice("🥤", "Cola", "No."),
                             WisdomChoice("🍬", "Candy", "No.")],
               grandma: "Sambar, then rasam, then curd rice to calm everything down.",
               science: "Curd has probiotics, and its coolness soothes a mouth after spicy food.",
               evidence: .some, allergens: [.dairy], diet: .vegetarian),
        Wisdom("mint-tea", .afterMeal, .afterMeal, "Mint Tea", "🌱",
               cultures: ["levantine"], origin: "Middle Eastern and North African homes",
               question: "After lunch, what does Teta pour into little glasses?",
               answer: WisdomChoice("🌱", "Fresh mint tea", "Mint may soothe the tummy after a big meal."),
               distractors: [WisdomChoice("🥤", "Cola", "No."),
                             WisdomChoice("🍬", "Candy", "No."),
                             WisdomChoice("🍦", "A huge ice cream", "Too much!")],
               grandma: "Mint tea is poured for every guest. It means welcome.",
               science: "Peppermint can relax the tummy muscles. Go easy on the sugar!",
               evidence: .some),

        Wisdom("thali-balance", .balancedPlate, .balance, "The Balanced Thali", "🍽️",
               origin: "Homes across India",
               question: "Which plate would {elder} call a proper meal?",
               answer: WisdomChoice("🍛", "Dal, sabzi, roti or rice, curd and salad", "Every group of food in one plate!"),
               distractors: [WisdomChoice("🍟", "Only fried snacks", "Too much oil, too few helpers."),
                             WisdomChoice("🍚", "Just a big pile of rice", "Missing protein and vegetables."),
                             WisdomChoice("🍰", "Only sweets", "That's a party, not a meal!")],
               grandma: "A thali has a little of everything: grain, dal, sabzi, curd, salad and a bit of pickle.",
               science: "Different foods bring different nutrients. A mix of grains, pulses, vegetables and dairy covers most of what you need.",
               evidence: .strong),
        Wisdom("bitter-first", .balancedPlate, .balance, "Bitter First", "🥗",
               cultures: ["bengali", "odia"], origin: "Bengali homes",
               question: "In a Bengali meal, which dish is eaten first?",
               answer: WisdomChoice("🥗", "Shukto, something bitter", "Bengali meals go from bitter to sweet!"),
               distractors: [WisdomChoice("🍮", "Mishti doi", "That's the very last course."),
                             WisdomChoice("⚪️", "Rosogolla", "That comes at the end."),
                             WisdomChoice("🐟", "The fish curry", "That comes in the middle.")],
               grandma: "Shukto or a bitter fry starts the meal, then dal, vegetables, fish, chutney and something sweet at the end.",
               science: "Bitter vegetables like karela are full of fiber and helpers. Starting with them is a tradition to wake up the appetite; scientists are still studying that part.",
               evidence: .tradition),
        Wisdom("ichiju-sansai", .balancedPlate, .balance, "One Soup, Three Sides", "🍱",
               cultures: ["japanese"], origin: "Japanese homes",
               question: "What does a balanced Japanese home meal look like?",
               answer: WisdomChoice("🍱", "Rice, a soup and three small side dishes", "Ichiju-sansai: a little of many things."),
               distractors: [WisdomChoice("🍜", "Just instant noodles", "That's a sometimes food."),
                             WisdomChoice("🍬", "Candy", "No."),
                             WisdomChoice("🍰", "Cake", "No.")],
               grandma: "Ichiju-sansai means one soup and three sides, always with rice.",
               science: "Many small dishes mean many different vegetables, proteins and nutrients.",
               evidence: .strong),
        Wisdom("milpa-plate", .balancedPlate, .balance, "The Three Sisters", "🌽",
               cultures: ["mexican"], origin: "Mexican homes",
               question: "Which three foods grow together and fill Abuela's plate?",
               answer: WisdomChoice("🌽", "Corn, beans and squash", "The three sisters!"),
               distractors: [WisdomChoice("🍬", "Candy, soda and chips", "No!"),
                             WisdomChoice("🍰", "Cake, cookies and pie", "No."),
                             WisdomChoice("🧊", "Ice, ice and more ice", "No.")],
               grandma: "Corn, beans and squash are planted together and eaten together.",
               science: "Grain + legume + vegetable together give energy, complete protein and vitamins.",
               evidence: .strong),

        Wisdom("good-breakfast", .breakfast, .timing, "Breakfast Before School", "🌅",
               origin: "Homes everywhere",
               question: "{name} is late for school. What does {elder} insist on?",
               answer: WisdomChoice("🥣", "Sit down and eat a proper breakfast", "Breakfast fuels the brain for the morning."),
               distractors: [WisdomChoice("🏃", "Skip breakfast and run", "Your brain will run out of fuel!"),
                             WisdomChoice("🍪", "Just a biscuit in the car", "Not enough fuel."),
                             WisdomChoice("🍬", "Candy on the bus", "A quick zoom, then a crash.")],
               grandma: "Nobody leaves the house without eating. Poha, upma, paratha, idli or a glass of milk at least!",
               science: "Studies show children who eat a good breakfast pay attention and remember better at school.",
               evidence: .strong),
        Wisdom("hundred-steps", .afterDinnerWalk, .timing, "A Slow Walk After Dinner", "🚶",
               origin: "Homes across India",
               question: "Dinner is done. What does Dadaji always do?",
               answer: WisdomChoice("🚶", "Take a slow little walk", "A gentle walk helps your body handle the meal."),
               distractors: [WisdomChoice("🛌", "Lie down straight away", "Better to wait a while."),
                             WisdomChoice("🏃", "Run a race", "Too fast after a full tummy!"),
                             WisdomChoice("📺", "Watch TV with a snack", "Not after dinner.")],
               grandma: "Grandparents say walk a hundred slow steps after dinner, called shatapavali.",
               science: "A short, gentle walk after eating helps keep blood sugar steady and can ease digestion.",
               evidence: .strong),
    ]

    // MARK: Combos spotted on the plate

    static let combos: [Combo] = [
        Combo(id: "complete-protein", title: "Dal + Grain = Complete Protein", emoji: "🍛", rule: .legumeAndGrain,
              explanation: "Dals and beans plus a grain give every protein building block. That's why grandmas serve them together!"),
        Combo(id: "iron-vitc", title: "Iron + Vitamin C Team", emoji: "🍋", rule: .nutrients([.iron, .vitaminC]),
              explanation: "Vitamin C helps your body absorb the iron in plant foods, like lemon on dal."),
        Combo(id: "fat-vita", title: "Vitamin A + a Little Fat", emoji: "🥕", rule: .nutrients([.vitaminA, .healthyFats]),
              explanation: "Vitamin A needs a little fat, like ghee, oil or coconut, to get into your body."),
        Combo(id: "calcium-d", title: "Calcium + Vitamin D", emoji: "🦴", rule: .nutrients([.calcium, .vitaminD]),
              explanation: "Vitamin D helps your bones soak up calcium."),
        Combo(id: "tummy-team", title: "Good Bacteria + Fiber", emoji: "🦠", rule: .nutrients([.probiotics, .fiber]),
              explanation: "Fiber is food for the friendly bacteria in curd and fermented foods."),
    ]

    /// Dishes built around dals, beans or soy.
    static let legumeDishes: Set<String> = [
        "arhar-dal", "lauki-chana", "moong-chilla", "moong-sprouts", "dal-dhokli", "moong-khichdi", "gatte", "papad-sabzi",
        "missi-roti", "dal-baati", "dhokla", "khandvi", "handvo", "khichdi-kadhi", "gujarati-thali", "dalma", "chakuli-pitha",
        "ghanta", "bhaja-moong", "jhal-muri", "litti-chokha", "sattu-drink", "ghugni", "dal-pitha", "khar", "rajma-chawal",
        "chole-roti", "kali-dal", "kashmiri-rajma", "sai-bhaji", "sindhi-kadhi", "tidali-dal", "varan-bhaat", "thalipeeth",
        "bhakri-pithla", "misal-usal", "idli-sambar", "dosa-chutney", "ven-pongal", "sundal", "puttu-kadala", "kanji-payar",
        "pesarattu", "gongura-pappu", "tomato-pappu", "bisi-bele-bath", "kosambari", "roasted-chana", "miso-soup", "edamame",
        "mapo-tofu-mild", "doenjang", "frijoles", "sopa-lentejas", "hummus", "shorbat-adas", "minestrone", "pasta-fagioli",
        "red-red", "moi-moi", "misir-wat", "shiro", "beans-toast", "pb-sandwich",
    ]

    /// Dishes built around a grain or millet.
    static let grainDishes: Set<String> = [
        "arhar-dal", "veg-dalia", "aloo-methi-roti", "dal-dhokli", "moong-khichdi", "rajgira-thepla", "bajra-roti", "raab",
        "missi-roti", "dal-baati", "methi-thepla", "handvo", "khichdi-kadhi", "muthiya", "gujarati-thali", "pakhala",
        "chakuli-pitha", "macher-jhol", "jhal-muri", "litti-chokha", "chura-dahi", "dal-pitha", "jolpan", "saag-makki",
        "rajma-chawal", "chole-roti", "aloo-paratha", "kashmiri-rajma", "sai-bhaji", "koki", "kanda-poha", "varan-bhaat",
        "thalipeeth", "bhakri-pithla", "idli-sambar", "dosa-chutney", "ven-pongal", "rasam-rice", "curd-rice", "ragi-koozh",
        "puttu-kadala", "appam-stew", "kanji-payar", "ragi-sangati", "ragi-mudde", "bisi-bele-bath", "akki-rotti", "neer-dosa",
        "onigiri", "congee", "bibimbap", "corn-tortilla", "tabbouleh", "pasta-fagioli", "ricotta-toast", "jollof", "injera",
        "oatmeal-berries", "beans-toast", "pb-sandwich",
    ]

    // MARK: Ask your elders

    /// Questions children ask a grandparent or parent, then record the answer.
    static let elderQuestions: [String] = [
        "What did you eat when you had a cold as a child? Who made it for you?",
        "What did you eat for breakfast when you were my age?",
        "Which dish did your grandmother make that you miss the most?",
        "What did your family eat on hot summer days, and on cold winter days?",
        "Which foods should always go together, and which should never be mixed?",
        "What spices go in our dal, and why do we add them?",
        "What special food did you eat on festival days?",
        "Which home remedy do you trust the most? Who taught it to you?",
        "How did you learn to cook? What was the first thing you made?",
        "Did your family grow any food? What did you pick yourself?",
    ]

    static func wisdom(id: String) -> Wisdom? { all.first { $0.id == id } }
}
